server:
  port: 9002
spring:
  application:
    name: lm-account
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.74.129:3307/lm-account?characterEncode=UTF8
    username: root
    password: 123456
  rabbitmq:
    port: 5672
    host: 192.168.74.129
    username: guest
    password: guest
    listener:
          direct:
            acknowledge-mode: manual
          simple:
            acknowledge-mode: manual
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
