server:
  port: 8881
spring:
  application:
    name: tcc-account
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcc-account?characterEncode=UTF8
    username: root
    password: 123
    # 配置 TCC框架使用的数据源
    tcc:
      url: jdbc:mysql://localhost:3306/tcc?characterEncode=UTF8
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
