server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: lm-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.74.129:3306/lm-user?characterEncode=UTF8
    username: root
    password: 123456
  rabbitmq:
    port: 5672
    host: 192.168.74.129
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#重新发送间隔时间和最大重发次数配置
message:
  interval:
    time: 10
  resend:
    maxTimes: 5
